name: build

on: [push, pull_request]

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.14"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.2.1
      - name: Resolve dependencies
        run: poetry lock
      - name: Upload lock file
        uses: actions/upload-artifact@v7
        with:
          name: modern-poetry-lock
          path: poetry.lock
